server_id: ''
mysql:
  host: ''
  database: ''
  username: ''
  password: ''
mirai:
  qq: ''
  group: ''
whitelist: false
playerlistlogger: false
bukkit:
  commands_on_enable: []
  world_protection: []